name: build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
      
    steps:
    - name: setup
      run: |
        cd /home/
        mkdir -p ws_rmf/src
        cd ws_rmf/src
        git clone https://github.com/Yadunund/rmf_core
    - name: deps
      shell: bash
      run: |
        sudo apt update
        cd /home/ws_rmf
        source /opt/ros/eloquent/setup.bash
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
    - name: build
      shell: bash
      run: |
        cd /home/ws_rmf
        source /opt/ros/eloquent/setup.bash
        colcon build
